config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :entries
    resources :comments
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true
  validates :subject, presence: true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :correct_user, only: [:destroy]

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new entry_params
    @entry.user_id = params[:user_id]
    if @entry.save
      flash[:success] = "New entry created"
      redirect_to @entry
    else
      render :new
    end
  end

  def show
    @entry = Entry.find_by id: params[:id]
    @comments = @entry.comments.take(5)
  end

  def edit
    @entry = Entry.find_by id: params[:id]
  end

  def update
    @entry = Entry.find_by id: params[:id]
    if @entry.update_attributes entry_params
      flash[:success] = "Updated"
      redirect_to @entry
    else
      render :edit
    end
  end

  def destroy
    @entry = Entry.find_by id: params[:id]
    @entry.destroy
    flash[:success] = t("deleted")
    redirect_to root_path
  end

  private
  def entry_params
    params.require(:entry).permit :subject, :content, :picture
  end

  def correct_user
    @entry = Entry.find_by id: params[:id]
    redirect_to root_path unless @entry&.user.current_user? current_user
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/edit.html.erb
<h1>Edit Entry</h1>
<%= form_for @entry, url: @entry, method: :put do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :subject, value: @entry.subject %>
  </div>
  <div class="field">
    <%= f.text_area :content, value: @entry.content, rows: "8" %>
  </div>
  <div class="field">
    <%= hidden_field_tag "user_id", current_user.id %>
  </div>
  <%= f.submit t("post"), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

<script type="text/javascript">
  $('#entry_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/entries/new.html.erb
<h1>New Entry</h1>
<%= form_for @entry, url: entries_path, method: :post do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :subject, placeholder: "Enter subject..." %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new entry...", rows: "8" %>
  </div>
  <div class="field">
    <%= hidden_field_tag "user_id", current_user.id %>
  </div>
  <%= f.submit t("post"), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

<script type="text/javascript">
  $('#entry_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/entries/show.html.erb
<% if @entry.user.current_user? current_user %>
  <%= link_to t("edit"), edit_entry_path(@entry),
    class: "pull-right btn-sm btn-warning" %>
<% end %>
<h1><%= @entry.subject %></h1>
<%= image_tag @entry.picture.url, class: "center-block" if @entry.picture? %>
<p><%= @entry.content %></p>
<span class="timestamp">
  <%= t("posted") %> <%= time_ago_in_words @entry.created_at %> <%= t("ago") + " " + t("by") %>
  <%= link_to @entry.user.name, @entry.user %>
</span>
<hr>
<div class="row">
  <div class="col-md-6">
    <% if logged_in? %>
    <h2><%= t("comments") %></h2>
      <%= form_tag comments_path, method: "post" do %>
        <div class="field">
          <%= text_area_tag :content, "", rows: "3" %>
        </div>
        <%= hidden_field_tag "entry_id", @entry.id %>
        <%= submit_tag t("leave_comment"), class: "btn btn-primary" %>
      <% end %>
    <% end %>
    <% @comments.each do |comment| %>
      <div class="media" id="comment-<%= comment.id %>">
				<%= link_to gravatar_for(comment.user, size: Settings.user.gravatar.size), comment.user %>
					<h4><%= link_to @entry.user.name, @entry.user %></h4>
          <% if comment.user.current_user? current_user %>
            <div class="dropdown pull-right">
              <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
              <span class="caret"></span></button>
              <ul class="dropdown-menu" overflow-y="visible">
                <li>
                  <%= link_to t("edit"), edit_comment_path(comment), remote: true %>
                </li>
                <li>
                  <%= link_to t("delete"), comment, method: :delete, remote: true, data: {confirm: t("you_sure")} %>
                </li>
              </ul>
            </div>
          <% end %>
					<p><%= comment.content %></p>
          <%= form_tag comment, remote: true, method: "put", id: "comment-form-#{comment.id}", style: "display: none;" do %>
            <div class="field">
              <%= text_area_tag :content, "", rows: "2" %>
            </div>
            <%= hidden_field_tag "entry_id", @entry.id %>
            <%= submit_tag t("edit_comment"), class: "btn btn-primary" %>
          <% end %>
			</div>
    <% end %>
  </div>
</div>